import Navbars from "./Navbar"
import Hero from "./Hero"
import Services from "./Services"
import Whyus from "./Whyus"
import Testimonial from "./Testimonial"
import Banner from "./Banner"
import Footer from "./Footer"
import Faq from "./Faq"
import Owlcarousel from "./Owlcarousel"
export {Navbars, Hero, Services, Whyus, Testimonial, Banner, Footer, Faq, Owlcarousel}